### PR TITLE
Nicer cursor: hide normally, show in buffer in search mode

### LINKED ISSUE #7: Cursor is shown away from selection
The cursor is still visible at the end of the final item in the list, instead of where the current selection is highlighted, or where user input is editing the search buffer. It's distracting.

screen shot 2015-09-30 at 12 12 39 am

Seems like the cursor should be hidden in normal mode, and put at the end of the search buffer when editing the incremental search filter.

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #7

### CODE REVIEW

**Comment by psprint** [comment]
Could you remove the unnecessary double brackets "[["? I tried to be minimalistic with this, despite many people advising me to use it as the zsh way of doing ifs. I would stick to the minimalism in the project, use [[ only for special ZSH features and for complex conditions (&&, ||).

The cursor doesn't show when ZNT is called from ZLE. I have autoload znt-history-widget, zle -N znt-history-widget and bindkey "^R" znt-history-widget. N-history is then called from ZLE at ^R key press. Maybe you could figure out how to show cursor there. Found something on "standout" in zlezsh man page but it seems to be problematic. But that's not a big problem IMO, leaving the cursor absent when in ZLE.

**Comment by psprint** [comment]
It's interesting that the cvvis, civis codes in general work in Zle:

```zsh
zmodload zsh/terminfo
a() { echo $terminfo[civis]; sleep 5; echo $terminfo[cvvis]; }
zle -N a
bindkey "^T" a
```

**Comment by apjanke** [comment]
I've added a check that will leave the cursor visible when starting in search mode. The logic could probably be cleaned up to move all the `civis`/`cvvis` stuff to a single place in the `n-list` loop, though.

Also changed some of the double brackets to single brackets.

**Comment by psprint** [comment]
There is one [[ left at "while [[ -n "$chunk" ]]; do"

**Comment by apjanke** [comment]
Okay, got that one too now.

**Comment by psprint** [comment]
Cool that it's resolved with Zle. One thing – n-list-draw doesn't use $terminfo but there is zmodload zsh/terminfo in it

**Comment by apjanke** [comment]
Oops. Left over from when I had one of those `civis`/`cvvis` calls in `n-list-draw` instead of pulling it up to `n-list`. No real effect: `n-list-draw` is only called from `n-list`, so the module would already be loaded, right? But I've removed it to clean things up.

If `n-list-input` is strictly a helper function for `n-list`, could remove the `zmodload zsh/terminfo` call from it, too.

**Comment by psprint** [comment]
Right it would be already loaded. As for n-list-input, zmodload should be there, as the helper functions in my intention allow to build own n-list. n-preview does that, doesn't use n-list but instead n-list-{draw,input} directly. It's however problematic as it turns out. Didn't add incremental search to n-preview because handling this feature for two lists seemed to be monster amount of code. This hint's that instead of n-list-{draw,input} it should be something like n-list, that takes name of zcurses window (?) and handles mostly everything. That would result in what I intended – to be able to run as many lists as one wants

**Comment by psprint** [comment]
zmodload is still in n-list-draw at current moment

**Comment by apjanke** [comment]
Maybe I didn't get the `git push` right? I re-did `git push --force`. Check again; it looks gone to me now when I view it on the "Files changed" Github page for this PR.

**Comment by psprint** [comment]
It's good now. Sorry for not point that out earlier, but could you also remove:
- echo >&2 "Usage: n-list element_1 ..."
- local NLIST_START_IN_SEARCH_MODE=1

I would separate those changes into small commits. Also not sure about the >&2, I think most programs use &1 for help

**Comment by apjanke** [comment]
Yeah, I'll back them out and submit as separate PRs.

I think the `&>2` vs `&>1` for help should maybe be based on context: if you're seeing the help screen because you asked for it with `--help`, then it goes on `stdout`. But if you're seeing it because you gave the program an invalid set of arguments, then it's more of an error message, and should maybe go on `stderr`. Up to you, and sorry for being presumptuous there.

**Comment by apjanke** [comment]
Okay, I've revised this PR. Better now?

**Comment by psprint** [comment]
Yeah it's fine, merged

**Comment by apjanke** [comment]
Cool. I'm going to try to talk you in to the "`local`" change in a separate PR.

**Comment by apjanke** [comment]
By the way, good working with you!

**Comment by psprint** [comment]
PS. One can also call tput cvvis etc., and I'm thinking about adding a defensively written function "cursor_visibility", that would have the information about whether is terminfo module available, and if not, it would then try with tput. Wonder if there really are zsh builds without terminfo module, but it might be possible.

Thanks, good working with you too. I'll be available in few hours

**Comment by apjanke** [comment]
Re: your 
>  Right it would be already loaded. As for n-list-input,

... it sounds almost like instead of combining the `-draw` and `-input` functions, maybe they should stay helper functions as is, and `n-list` should be pushed down just a tiny bit, so instead of looking at `$COLUMNS` and `$LINES` and using the whole terminal window as its drawing area, you have an `n-list-win()` that's just like that, but takes an `ncurses` window as an input argument so it can draw & handle lists in sub-areas, and then `n-list` becomes a really thin wrapper where it just calls that `n-list-win()` with `stdscr` (the whole terminal window) as its window input.

But I don't know how you handle multiplexing user input from mutliple curses windows in that case and keep them both live. Maybe you push the event handling (input listening) loop up to the parent list function, and it passes inputs down to child window callbacks for processing? I'm kind of a `curses` newbie here, so I really don't know how this should work.

**Comment by apjanke** [comment]
> PS. One can also call tput cvvis etc., and I'm thinking about adding a defensively written function "cursor_visibility", ...

Yeah, and if you want to be conservative, you could also check for `tput`s that are only able to handle the two-character `termcap` entries instead of the longer `terminfo` capability names. I recently got burned by this with a change I made to the OMZ installer code in robbyrussell/oh-my-zsh#3664 / robbyrussel/oh-my-zsh#4404.

I think the defensive behavior to do here is:
* Is terminfo cursor vis/invis supported here? use that
* else is termcap cursor vis/invis supported here? use that
* else do nothing silently, leaving cursor in default state, and it'll work out

I bet there's a zsh-friendly way to do this concisely, but I'm not sure it is. I'll look in to it, since this is stuff I've been reading about lately. (I don't expect there's a POSIX-ly friendly or distro-independent way to do this, since the `terminfo` and `termcap` and Linux distro maintainers are not all on the same page.)

**Comment by apjanke** [comment]
> Wonder if there really are zsh builds without terminfo module, but it might be possible.

I am wondering this too now. Gotta be, since terminfo is an external library that might be completely absent, right? But terminfo is so common now I don't know if this is possible to really reproduce on modern systems.

I'm currently rolling my own zsh test builds with custom build options because I'm chasing down a [related issue](http://www.zsh.org/mla/workers/2015/msg02630.html). I'll see if this is still a feasible thing to do.

**Pull request merged**
