### PR TITLE
Allow installation with zsh-plugin-manager (zgen, antigen)

### PR DESCRIPTION
**Pull request by hcgraf**
Hi,
thank you for your effort, I really like these functions!

This PR just makes a minor modification to allow installation of these scripts with a zsh-plugin-manager (I tested it with zgen).

Zgen (antigen) works like this:
- Adds plugin directory to fpath
- Sources any scripts found in the toplevel directory

Therefore, to make your repository work as a plugin repository, the following modification were needed:
- Move install.sh script away from toplevel (otherwise it would be sourced with every shell start)
- Include a script which contains the .zshrc additions recommended by your README (plus the creation of the config-dir and files)
- Modified the README.md accordingly

Kind regards
Hagen Graf

### CODE REVIEW

**Comment by psprint** [comment]
How is the source done? Because "source n-cd", for example, isn't what should be done. The files are functions, recognized and ran by Zsh through "autoload n-cd" (in the example case). The fpath should be indeed set to ZNT main dir, that's fine. But then a few autoloads are only needed, not sourcing.

**Comment by hcgraf** [comment]
Yes, I understand. Only scripts (i.e. *.zsh, *.sh) are sourced. It's basically designed for this purpose ;)

**Comment by psprint** [comment]
I'm like merging your patch, only will need few hours for this

Best regards,
Sebastian Gniazdowski

**Comment by hcgraf** [comment]
Thank you!
(you might want to modify the path in the README from hcgraf/zsh-navigation-tools to psprint/zsh-navigation-tools)

**Comment by psprint** [comment]
I merged the PR. Installed zgen, sourced it from .zshrc, added the zgen load into my .zshrc. When first restarted shell, cloning message appeared:

Cloning into '/Users/sgniazdowski/.zgen/psprint/zsh-navigation-tools-master'...
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 33 (delta 6), reused 10 (delta 1), pack-reused 0
Unpacking objects: 100% (33/33), done.
Checking connectivity... done

But then the functions weren't in path:

12:05 [sgniazdowski@MACMINI:/Users/sgniazdowski/github]1# n-cd
zsh: n-cd: function definition file not found

The fpath is:
/Users/sgniazdowski/github/zgen /usr/share/zsh/site-functions /usr/share/zsh/5.0.2/functions

Seems the plugin's dir isn't within the path?

**Comment by psprint** [comment]
Antigen also seems to not work:

**Comment by hcgraf** [comment]
For zgen:
is your .zshrc of the following structure?
```
# load zgen
source "${HOME}/path/to/zgen/zgen.zsh"
# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"
    # load plugins
    zgen load psprint/zsh-navigation-tools
    # save all to init script
    zgen save
fi
```

What's in your /path/to/zgen/init.zsh? (that file should be generated)

**Comment by hcgraf** [comment]
After your commit b1035f9f86e0e921f8830fdff37608b21ae219c7, the plugin is in my fpath twice…

**Comment by psprint** [comment]
Ok I removed the fpath+=. Zgen seems to work. Antigen extends the fpath but then, no autoloads seem to be active, which means the *.zsh file isn't sourced

**Comment by hcgraf** [comment]
strange. according to Antigens README, it should work…
I had a short look at the source code, and I also didn't find anything which would prevent this to work. But I'm not using antigen myself, so I didn't test it.
Did you use `antigen apply` after `antigen bunde`?

**Comment by hcgraf** [comment]
OK, I also tried it. With a completely new user, empty home directory.
```
zsh
curl -L https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh > antigen.zsh
source antigen.zsh
antigen bundle psprint/zsh-navigation-tools
n-cd
```
works as expected.

**Comment by psprint** [comment]
Yes here is my zshrc snippet:

. ~/github/antigen/antigen.zsh
antigen bundle psprint/zsh-navigation-tools
antigen apply

fpath is set, but no znt autoloads are active

**Comment by hcgraf** [comment]
I tried that with my new user
```
git clone https://github.com/zsh-users/antigen.git ~/antigen
```
.zshrc:
```
. ~/antigen/antigen.zsh

antigen bundle psprint/zsh-navigation-tools
antigen apply
```
```
zsh
n-cd
```
It's working.

**Comment by psprint** [comment]
Thanks. Good that it's working I will investigate my setup in free time.

**Comment by psprint** [comment]
I investigated my setup and it turned out that when I tried antigen some time before, a clone of znt repo was created, which was then laying on disk without updates. That's quite weird, I though antigen would update plugins somehow. Without the update antigen never saw the commit from PR.

**Comment by hcgraf** [comment]
You need to use `antigen update` to update your plugins or use a plugin like https://github.com/unixorn/autoupdate-antigen.zshplugin to do this regularly for you (there is also https://github.com/unixorn/autoupdate-zgen for zgen)

If you tried antigen even before my initial PR, then every shell start would have sourced your install.sh script, which would have modified your zshrc…

**Comment by psprint** [comment]
It was before there was install.sh, antigen says it's compatible "with all"
github zsh repos, so I tried it on mine just like that. It didn't work
then, with no install.sh nor *.plugin.zsh

**Pull request merged**
